preferred_auth_method = "chatgpt"

model = "gpt-5.3-codex"
model_reasoning_summary = "auto"

approval_policy = "on-request"
sandbox_mode = "workspace-write"
model_reasoning_effort = "high"

web_search = "live"
personality = "pragmatic"

[sandbox_workspace_write]
network_access = true

